# Generated by Django 3.2.16 on 2024-05-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='departure_date',
            field=models.DateField(default='2024-05-05', verbose_name='Дата отправления'),
            preserve_default=False,
        ),
    ]
