# Generated by Django 3.2.16 on 2024-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_shipment_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='truck_actual_arrival_time_departure_point',
            field=models.DateField(default='2024-05-10', verbose_name='Вермя факт прибытия авто в пункт отправления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='truck_actual_arrival_time_destination_point',
            field=models.DateField(default='2024-05-10', verbose_name='Вермя факт прибытия авто в пункт назначения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='truck_actual_departure_time_departure_point',
            field=models.DateField(default='2024-05-11', verbose_name='Вермя факт отбытия авто из пункта отправления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='truck_actual_departure_time_destination_point',
            field=models.DateField(default='2024-05-11', verbose_name='Вермя факт отбытия авто из пункта назначения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination_point',
            field=models.CharField(max_length=150, verbose_name='Пункт назначения'),
        ),
    ]
