# Generated by Django 3.2.16 on 2024-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_auto_20240517_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='truck_actual_arrival_time_departure_point',
            field=models.DateField(blank=True, null=True, verbose_name='Вермя факт прибытия авто в пункт отправления'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='truck_actual_arrival_time_destination_point',
            field=models.DateField(blank=True, null=True, verbose_name='Вермя факт прибытия авто в пункт назначения'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='truck_actual_departure_time_departure_point',
            field=models.DateField(blank=True, null=True, verbose_name='Вермя факт отбытия авто из пункта отправления'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='truck_actual_departure_time_destination_point',
            field=models.DateField(blank=True, null=True, verbose_name='Вермя факт отбытия авто из пункта назначения'),
        ),
    ]
