# Generated by Django 3.2.16 on 2024-05-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_auto_20240517_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='arrival_date',
            field=models.DateField(default='2024-05-25', verbose_name='Дата прибытия'),
            preserve_default=False,
        ),
    ]
